title: Sanjula's Dev Notes
description: Engineering notes on backend development, git, and tooling.
url: "https://sanjula-rtc.github.io"
baseurl: ""

author:
  name: Sanjula Lakpahana

theme: minima

minima:
  skin: dark

plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /posts/:slug/

show_excerpts: true
